#-------------------------------------------------------------
# Docker compose related with database services
#-------------------------------------------------------------
version: '3.8'

services:
  # MariaDB
  # A database Nginx Proxy Manager and Umami
  db:
    container_name: db
    image: mariadb
    restart: unless-stopped
    volumes:
      - ${SELF_HOME_DIR}/mariadb/dbdata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ${SELF_HOME_DIR}/db:/docker-entrypoint-initdb.d # FIX entrypoint
    env_file:
      - .env

  # Adminer
  # A dead-simple database manager
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8082:8080
    depends_on:
      - db

  # PostgreSQL
  # PostgreSQL is a powerful, open source object-relational database system 
  # with over 30 years of active development that has earned it a strong reputation for reliability, feature robustness, and performance
  # https://www.postgresql.org/
  postgres:
    image: postgres:12
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ${SELF_HOME_DIR}/postgres:/var/lib/postgresql/data
  # Redis
  # An in-memory data structure store, used as a distributed, in-memory key–value database, cache and message broker, with optional durability. 
  # https://redis.io/
  redis:
    image: 'redis'
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  # pgAdmin
  # pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL, 
  # the most advanced Open Source database in the world.
  # https://www.pgadmin.org/
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ${SELF_HOME_DIR}/pgadmin:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
