#-------------------------------------------------------------
# Docker compose related with servers
#-------------------------------------------------------------
version: '3.8'

services:
  # Nginx Proxy Manager
  # Nice and simple Nginx UI for managing reverse proxy
  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80 # HTTP port
      - 443:443 # HTTPS port
      - 8081:81 # Admin Paner port
    environment:
      DB_MYSQL_HOST: ${MYSQL_HOST}
      DB_MYSQL_PORT: ${MYSQL_PORT}
      DB_MYSQL_USER: ${MYSQL_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: 'nginxproxymanager'
    volumes:
      - ${SELF_HOME_DIR}/nginx-proxy-manager/data:/data
      - ${SELF_HOME_DIR}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ${SELF_HOME_DIR}/nginx-proxy-manager/log:/var/log
    depends_on:
      - db
